// import type { Metadata } from "next";
// import { Poppins } from "next/font/google";
// import "@/app/globals.css";
import RouteBanner from "@/components/layout/route-banner";
import ServicesOverview from "@/components/layout/services-overview";

// const poppins = Poppins({
//     weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//     subsets: ["latin", "latin-ext"],
//     variable: "--poppins",
// });

// export const metadata: Metadata = {
//     title: "ecommerce",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <RouteBanner />
            {children}
            <ServicesOverview />
        </>
    );
}
