import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";

const poppins = Poppins({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
    subsets: ["latin", "latin-ext"],
    variable: "--poppins",
});

export const metadata: Metadata = {
    title: "ecommerce",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${poppins.variable} antialiased`}>
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
